name: Generate C++
on: push
jobs:
  golang:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Check out code
      uses: actions/checkout@v3

    - name: Generate C++ code
      run: |
        protoc -I . *.proto --cpp_out /tmp
